### ISSUE TITLE
Error from server (Forbidden): error when creating "rbac.yml": clusterroles.rbac.authorization.k8s.io "kube-cert-manager" is forbidden

### ISSUE THREAD

**Issue by cmwendwa** [bonovoxly/gke-nginx-ingress-controller#1]
`serviceaccount "kube-cert-manager" created
clusterrolebinding "kube-cert-manager-service-account" created
Error from server (Forbidden): error when creating "rbac.yml": clusterroles.rbac.authorization.k8s.io "kube-cert-manager" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["certificates"], APIGroups:["*"], Verbs:["get"]} PolicyRule{Resources:["certificates"], APIGroups:["*"], Verbs:["list"]} PolicyRule{Resources:["certificates"], APIGroups:["*"], Verbs:["watch"]} PolicyRule{Resources:["ingresses"], APIGroups:["*"], Verbs:["get"]} PolicyRule{Resources:["ingresses"], APIGroups:["*"], Verbs:["list"]} PolicyRule{Resources:["ingresses"], APIGroups:["*"], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:["*"], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:["*"], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:["*"], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:["*"], Verbs:["update"]} PolicyRule{Resources:["secrets"], APIGroups:["*"], Verbs:["delete"]} PolicyRule{Resources:["events"], APIGroups:["*"], Verbs:["create"]}] user=&{myemail@domain.com  [system:authenticated] map[authenticator:[GKE]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
W0305 10:32:31.423048   79810 factory_object_mapping.go:423] Failed to download OpenAPI (Get https://35.224.167.168/swagger-2.0.0.pb-v1: net/http: TLS handshake timeout), falling back to swagger
customresourcedefinition "certificates.stable.k8s.psg.io" created
Error from server (AlreadyExists): error when creating "pvc.yml": persistentvolumeclaims "kube-cert-manager-data" already exists
deployment "kube-cert-manager" created`

Got this error while following the tutorial here: https://blog.billyc.io/2017/12/27/deploying-and-using-kube-cert-manager-with-an-nginx-ingress-controller-on-kubernetes/

**Comment by bonovoxly** [comment]
Did you give yourself cluster-admin? https://github.com/bonovoxly/gke-nginx-ingress-controller#requirement---cluster-admin

I mention it in this repo, but I do not mention it in the [kube-cert-manager](https://github.com/bonovoxly/gke-kube-cert-manager). I might be needed for both.

**Comment by bonovoxly** [comment]
Updated the readme to require cluster admin.
